FROM golang:1.20.6-bullseye as builder

WORKDIR /app

COPY go.* ./

RUN go mod download

COPY . .

RUN go build -o main /app/main.go

FROM debian:bullseye-slim

WORKDIR /app

RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["/app/main"]
